
#define PROCEDURALTEXTURESLIBRARY_PROJECT_NAME        "ProceduralTexturesLibrary"
#define PROCEDURALTEXTURESLIBRARY_PROJECT_DESCRIPTION ""

#define PROCEDURALTEXTURESLIBRARY_AUTHOR_ORGANIZATION ""
#define PROCEDURALTEXTURESLIBRARY_AUTHOR_DOMAIN       ""
#define PROCEDURALTEXTURESLIBRARY_AUTHOR_MAINTAINER   ""

#define PROCEDURALTEXTURESLIBRARY_VERSION_MAJOR       "4"
#define PROCEDURALTEXTURESLIBRARY_VERSION_MINOR       "0"
#define PROCEDURALTEXTURESLIBRARY_VERSION_PATCH       "0"
#define PROCEDURALTEXTURESLIBRARY_VERSION_REVISION    "aea1e09b67e8"

#define PROCEDURALTEXTURESLIBRARY_VERSION             "4.0.0"
#define PROCEDURALTEXTURESLIBRARY_NAME_VERSION        " v4.0.0 (aea1e09b67e8)"
