
#ifndef BABYLON_SHARED_EXPORT_H
#define BABYLON_SHARED_EXPORT_H

#ifdef PROCEDURALTEXTURESLIBRARY_STATIC_DEFINE
#  define BABYLON_SHARED_EXPORT
#  define PROCEDURALTEXTURESLIBRARY_NO_EXPORT
#else
#  ifndef BABYLON_SHARED_EXPORT
#    ifdef ProceduralTexturesLibrary_EXPORTS
        /* We are building this library */
#      define BABYLON_SHARED_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define BABYLON_SHARED_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef PROCEDURALTEXTURESLIBRARY_NO_EXPORT
#    define PROCEDURALTEXTURESLIBRARY_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef PROCEDURALTEXTURESLIBRARY_DEPRECATED
#  define PROCEDURALTEXTURESLIBRARY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef PROCEDURALTEXTURESLIBRARY_DEPRECATED_EXPORT
#  define PROCEDURALTEXTURESLIBRARY_DEPRECATED_EXPORT BABYLON_SHARED_EXPORT PROCEDURALTEXTURESLIBRARY_DEPRECATED
#endif

#ifndef PROCEDURALTEXTURESLIBRARY_DEPRECATED_NO_EXPORT
#  define PROCEDURALTEXTURESLIBRARY_DEPRECATED_NO_EXPORT PROCEDURALTEXTURESLIBRARY_NO_EXPORT PROCEDURALTEXTURESLIBRARY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PROCEDURALTEXTURESLIBRARY_NO_DEPRECATED
#    define PROCEDURALTEXTURESLIBRARY_NO_DEPRECATED
#  endif
#endif

#endif /* BABYLON_SHARED_EXPORT_H */
