#define BABYLONCPP_PROJECT_NAME        "BabylonCpp"
#define BABYLONCPP_PROJECT_DESCRIPTION "BabylonCpp - A port of Babylon.js to C++"

#define BABYLONCPP_AUTHOR_ORGANIZATION ""
#define BABYLONCPP_AUTHOR_DOMAIN       ""
#define BABYLONCPP_AUTHOR_MAINTAINER   ""

#define BABYLONCPP_VERSION_MAJOR       "4"
#define BABYLONCPP_VERSION_MINOR       "0"
#define BABYLONCPP_VERSION_PATCH       "0"
#define BABYLONCPP_VERSION_REVISION    "44db9a9609b0"

#define BABYLONCPP_VERSION             "4.0.0"
#define BABYLONCPP_NAME_VERSION        " v4.0.0 (44db9a9609b0)"
