
#define MATERIALSLIBRARY_PROJECT_NAME        "MaterialsLibrary"
#define MATERIALSLIBRARY_PROJECT_DESCRIPTION ""

#define MATERIALSLIBRARY_AUTHOR_ORGANIZATION ""
#define MATERIALSLIBRARY_AUTHOR_DOMAIN       ""
#define MATERIALSLIBRARY_AUTHOR_MAINTAINER   ""

#define MATERIALSLIBRARY_VERSION_MAJOR       "4"
#define MATERIALSLIBRARY_VERSION_MINOR       "0"
#define MATERIALSLIBRARY_VERSION_PATCH       "0"
#define MATERIALSLIBRARY_VERSION_REVISION    "44db9a9609b0"

#define MATERIALSLIBRARY_VERSION             "4.0.0"
#define MATERIALSLIBRARY_NAME_VERSION        " v4.0.0 (44db9a9609b0)"
